# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: EUPL-1.2

[bindings.kotlin]
package_name = "se.digg.opaque_ke_uniffi"
cdylib_name = "opaque_ke_uniffi"
